#!/usr/bin/env bash

echo 'speaking of variables'
echo 'they are set like so'
counter=0
test $counter == 1 # and are accessed by `$`

echo 'but spaces are no good'
counter = 1

echo 'variables can be set to lots of things'
string="my string"
number=0
float=0.5
undefined=
command_output=$(echo this is my output!)

echo 'and we can interpolate them in doubly quoted strings'
test "$string" == "$command_output"

echo 'they can be used in calculations'
answer=$number++
test $answer == 2

echo 'and as commands'
command="pwd"
$command

echo "there are some 'magical' variables in bash"
echo "homedir: $HOME"
echo "last exit code: $?"
echo "process id: $$"
echo "current dir: $PWD"

test "$PWD" == `foobar`

echo 'and the list goes on'
echo 'more info here: http://tldp.org/LDP/abs/html/internalvariables.html'
